# User config
author: "iiee iiee"
tagline: "iiee tagline"
description: "iiee desc"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "iiee@naver.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
url    : "https://iiee0.github.io"
baseurl: "/iiee"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed